# Generated by Django 3.2.4 on 2021-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
                ('inference_time', models.DateTimeField()),
                ('inner_uuid', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=50)),
            ],
        ),
    ]
