# Generated by Django 3.2.4 on 2021-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='origin_file_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
