# Generated by Django 3.2.4 on 2021-11-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_model', '0002_case_origin_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelquery',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='run_model.case')),
                ('state', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='file_type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
