# Generated by Django 3.2.4 on 2021-12-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_model', '0003_auto_20211130_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelpredict',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='run_model.case')),
                ('predict_path', models.CharField(max_length=100)),
                ('predict_prob_0', models.FloatField()),
                ('predict_prob_1', models.FloatField()),
                ('predict_prob_2', models.FloatField()),
                ('predict_prob_3', models.FloatField()),
                ('predict_prob_4', models.FloatField()),
                ('predict_prob_5', models.FloatField()),
                ('predict_prob_6', models.FloatField()),
                ('predict_prob_7', models.FloatField()),
                ('predict_prob_8', models.FloatField()),
                ('predict_prob_9', models.FloatField()),
                ('predict_prob_10', models.FloatField()),
                ('predict_prob_11', models.FloatField()),
                ('predict_prob_12', models.FloatField()),
                ('predict_prob_13', models.FloatField()),
                ('predict_prob_14', models.FloatField()),
                ('predict_prob_15', models.FloatField()),
            ],
        ),
    ]
