# Generated by Django 3.2.4 on 2021-12-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_model', '0004_modelpredict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='run_model.case')),
                ('comment', models.CharField(max_length=500)),
                ('is_incorrect', models.BooleanField()),
                ('is_difficult', models.BooleanField()),
            ],
        ),
    ]
