# Generated by Django 3.2.4 on 2022-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_model', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='report_missed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
